version: '3.8'
services:
  db:
    image: mysql:8.0.35
    container_name: reservation-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-p4ssw0rd}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-reservation}
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build: .
    container_name: reservation-app
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
volumes:
  db_data:
